import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					The weather app's <span>privacy policy!</span>
				</h1>
				<h3>Privacy Policy</h3>
				<p>
					Bob Lam built the Bob's Weather App app as a Free app. This SERVICE is provided by Bob Lam at no
					cost and is intended for use as is. This page is used to inform visitors regarding my policies with
					the collection, use, and disclosure of Personal Information if anyone decided to use my Service. If
					you choose to use my Service, then you agree to the collection and use of information in relation to
					this policy. The Personal Information that I collect is used for providing and improving the
					Service. I will not use or share your information with anyone except as described in this Privacy
					Policy. The terms used in this Privacy Policy have the same meanings as in our Terms and Conditions,
					which are accessible at Bob's Weather App unless otherwise defined in this Privacy Policy.
				</p>
				<h3>Log Data</h3>
				<p>
					I want to inform you that whenever you use my Service, in a case of an error in the app I collect
					data and information (through third-party products) on your phone called Log Data. This Log Data may
					include information such as your device Internet Protocol (“IP”) address, device name, operating
					system version, the configuration of the app when utilizing my Service, the time and date of your
					use of the Service, and other statistics.
				</p>

				<h3>Changes to This Privacy Policy</h3>
				<p>
					I may update our Privacy Policy from time to time. Thus, you are advised to review this page
					periodically for any changes. I will notify you of any changes by posting the new Privacy Policy on
					this page.
				</p>
				<p>This policy is effective as of 2022-01-23</p>
				<h3>Contact Us</h3>
				<p>
					If you have any questions or suggestions about my Privacy Policy, do not hesitate to contact me at
					boblam.ceo@gmail.com.
				</p>
			</main>

			<footer className={styles.footer}>
				<a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{' '}
					<span className={styles.logo}>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a>
			</footer>
		</div>
	);
}
